name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2  # Use v2 here for the latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://cloudformation.yml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name my-stack-name \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --parameter-overrides AWS_KEY_NAME=${{ secrets.AWS_KEY_NAME }}

      - name: Output Stack Information
        run: |
          aws cloudformation describe-stacks --stack-name my-stack-name
